#pragma once
#include "CoreMinimal.h"
#include "EIGS_CharacterID.generated.h"

UENUM(BlueprintType)
enum class EIGS_CharacterID : uint8 {
    Char_Unknown = 255 UMETA(DisplayName=Unknown),
    Char_Gen_M_Thug = 0 UMETA(DisplayName="Gen M Thug"),
    Char_Gen_Start = Char_Gen_M_Thug UMETA(DisplayName="Gen Start"),
    Char_Gen_M_Thief UMETA(DisplayName="Gen M Thief"),
    Char_Gen_M_Hitman UMETA(DisplayName="Gen M Hitman"),
    Char_Gen_M_Gangster UMETA(DisplayName="Gen M Gangster"),
    Char_Gen_MAX UMETA(Hidden),
    Char_Gen_End = Char_Gen_M_Gangster UMETA(DisplayName="Gen End"),
    Char_Gen_Limit = 63 UMETA(DisplayName="Gen Limit"),
    Char_Cracker UMETA(DisplayName=Cracker),
    Char_Unique_Start = Char_Cracker UMETA(DisplayName="Unique Start"),
    Char_Ropes UMETA(DisplayName=Ropes),
    Char_Chase UMETA(DisplayName=Chase),
    Char_Tulip UMETA(DisplayName=Tulip),
    Char_Zulu UMETA(DisplayName=Zulu),
    Char_Mozart UMETA(DisplayName=Mozart),
    Char_Tuna UMETA(DisplayName=Tuna),
    Char_Wiz UMETA(DisplayName=Wiz),
    Char_Ranger UMETA(DisplayName=Ranger),
    Char_Jupiter UMETA(DisplayName=Jupiter),
    Char_Clutch UMETA(DisplayName=Clutch),
    Char_Forehand UMETA(DisplayName=Forehand),
    Char_Stinger UMETA(DisplayName=Stinger),
    Char_Smoke UMETA(DisplayName=Smoke),
    Char_Runway UMETA(DisplayName=Runway),
    Char_Theresa UMETA(DisplayName=Theresa),
    Char_Peak UMETA(DisplayName=Peak),
    Char_Lector UMETA(DisplayName=Lector),
    Char_Vamp UMETA(DisplayName=Vamp),
    Char_Silver UMETA(DisplayName=Silver),
    Char_Volk UMETA(DisplayName=Volk),
    Char_HieloQP UMETA(DisplayName="Hielo QP"),
    Char_DollarDragonQP UMETA(DisplayName="Dollar Dragon QP"),
    Char_GenericQP_01 UMETA(DisplayName="Generic QP 01"),
    Char_GenericQP_02 UMETA(DisplayName="Generic QP 02"),
    Char_GenericQP_03 UMETA(DisplayName="Generic QP 03"),
    Char_GenericQP_04 UMETA(DisplayName="Generic QP 04"),
    Char_GenericQP_05 UMETA(DisplayName="Generic QP 05"),
    Char_GenericQP_06 UMETA(DisplayName="Generic QP 06"),
    Char_Robot UMETA(DisplayName=Robot),
    Char_Max_Jupiter UMETA(DisplayName="Max Jupiter"),
    Char_Max_Wiz1 UMETA(DisplayName="Max Wiz 1"),
    Char_Max_Wiz2 UMETA(DisplayName="Max Wiz 2"),
    Char_Max_Cracker UMETA(DisplayName="Max Cracker"),
    Char_Max_Vamp UMETA(DisplayName="Max Vamp"),
    Char_Max_Theresa UMETA(DisplayName="Max Theresa"),
    Char_Max_Volk UMETA(DisplayName="Max Volk"),
    Char_Max_Chase UMETA(DisplayName="Max Chase"),
    Char_PlayableEmployee UMETA(DisplayName="Playable Employee"),
    Char_Employee_Technician UMETA(DisplayName="Employee Technician"),
    Char_Recon_Ninja UMETA(DisplayName="Recon Ninja"),
    Char_Unique_MAX UMETA(Hidden),
    Char_Unique_End = Char_Recon_Ninja UMETA(DisplayName="Unique End"),
    Char_Unique_Limit = 223 UMETA(DisplayName="Unique Limit"),
    Char_Boss_Baker UMETA(DisplayName="Boss Baker"),
    Char_Boss_Start = Char_Boss_Baker UMETA(DisplayName="Boss Start"),
    Char_Boss_Hand UMETA(DisplayName="Boss Hand"),
    Char_Boss_Agent UMETA(DisplayName="Boss Agent"),
    Char_Boss_Captain UMETA(DisplayName="Boss Captain"),
    Char_Boss_Secretary UMETA(DisplayName="Boss Secretary"),
    Char_Boss_BakerQP UMETA(DisplayName="Boss Baker QP"),
    Char_Boss_CaptainQP UMETA(DisplayName="Boss Captain QP"),
    Char_Boss_Player UMETA(DisplayName="Boss Player"),
    Char_Boss_MAX UMETA(Hidden),
    Char_Boss_End = Char_Boss_Player UMETA(DisplayName="Boss End"),
    Char_Boss_Limit = 254 UMETA(DisplayName="Boss Limit"),
};
