#pragma once
#include "CoreMinimal.h"
#include "EIGS_AIMontageSOVariant.generated.h"

UENUM(BlueprintType)
enum class EIGS_AIMontageSOVariant : uint8 {
    SO_Unknown = 255 UMETA(DisplayName=Unknown),
    SO_Yawn = 0 UMETA(DisplayName=Yawn),
    SO_WatchTime UMETA(DisplayName="Watch Time"),
    SO_Adjust UMETA(DisplayName=Adjust),
    SO_Stretch UMETA(DisplayName=Stretch),
    SO_EnterCode UMETA(DisplayName="Enter Code"),
    SO_PressButton UMETA(DisplayName="Press Button"),
    SO_SwipeCard UMETA(DisplayName="Swipe Card"),
    SO_UseWaterDispence UMETA(DisplayName="Use Water Dispence"),
    SO_PickingUpFloor UMETA(DisplayName="Picking Up Floor"),
    SO_PaintingAlign UMETA(DisplayName="Painting Align"),
    SO_DoorUnlock_Left UMETA(DisplayName="Door Unlock Left"),
    SO_DoorUnlock_Right UMETA(DisplayName="Door Unlock Right"),
    SO_WaveHand_ComeOn UMETA(DisplayName="Wave Hand Come On"),
    SO_WaveHand_Angry UMETA(DisplayName="Wave Hand Angry"),
    SO_WaveHand_Hello UMETA(DisplayName="Wave Hand Hello"),
    SO_MeetingPresenter UMETA(DisplayName="Meeting Presenter"),
    SO_IDLE_Female UMETA(DisplayName="IDLE Female"),
    SO_Use_Phone_Wall UMETA(DisplayName="Use Phone Wall"),
    SO_Use_Phone_Table UMETA(DisplayName="Use Phone Table"),
    SO_Press_Button_On_Table UMETA(DisplayName="Press Button On Table"),
    SO_Press_Button_Under_Table UMETA(DisplayName="Press Button Under Table"),
    SO_Surprise UMETA(DisplayName=Surprise),
    SO_TakeDown UMETA(DisplayName="Take Down"),
    SO_BeignTakenDown UMETA(DisplayName="Beign Taken Down"),
    SO_Throw UMETA(DisplayName=Throw),
    SO_Pickup UMETA(DisplayName=Pickup),
    SO_L_Idle = 127 UMETA(DisplayName="L Idle"),
    SO_L_WalkieTalkie UMETA(DisplayName="L Walkie Talkie"),
    SO_L_HoldButton UMETA(DisplayName="L Hold Button"),
    SO_L_HoldingButtonOnTable = 144 UMETA(DisplayName="L Holding Button On Table"),
    SO_L_HoldingButtonUnderTable UMETA(DisplayName="L Holding Button Under Table"),
    SO_L_LookOut_Left = 131 UMETA(DisplayName="L Look Out Left"),
    SO_L_LookOut_Right UMETA(DisplayName="L Look Out Right"),
    SO_L_LookOut_Front UMETA(DisplayName="L Look Out Front"),
    SO_L_LookOut_Ground UMETA(DisplayName="L Look Out Ground"),
    SO_L_LookOut_Up UMETA(DisplayName="L Look Out Up"),
    SO_L_LookOut_Up_Slightly UMETA(DisplayName="L Look Out Up Slightly"),
    SO_L_LookOut_Corner_Left UMETA(DisplayName="L Look Out Corner Left"),
    SO_L_LookOut_Corner_Right UMETA(DisplayName="L Look Out Corner Right"),
    SO_L_LookOut_Under_Table UMETA(DisplayName="L Look Out Under Table"),
    SO_L_LookOut_Under_Car UMETA(DisplayName="L Look Out Under Car"),
    SO_L_SitFloor_Beggar = 150 UMETA(DisplayName="L Sit Floor Beggar"),
    SO_L_SitChair_Reading UMETA(DisplayName="L Sit Chair Reading"),
    SO_L_Sit_Bench_Center = 172 UMETA(DisplayName="L Sit Bench Center"),
    SO_L_Sit_Table_FeetOn = 154 UMETA(DisplayName="L Sit Table Feet On"),
    SO_L_Sit_Table UMETA(DisplayName="L Sit Table"),
    SO_L_Sit_Table_2 = 161 UMETA(DisplayName="L Sit Table 2"),
    SO_L_Sit_Desk UMETA(DisplayName="L Sit Desk"),
    SO_L_Sit_Table_FeetOn_Right = 164 UMETA(DisplayName="L Sit Table Feet On Right"),
    SO_L_Sit_Sofa_Center = 167 UMETA(DisplayName="L Sit Sofa Center"),
    SO_L_Sit_Sofa_Left UMETA(DisplayName="L Sit Sofa Left"),
    SO_L_Sit_Sofa_Right UMETA(DisplayName="L Sit Sofa Right"),
    SO_L_FixingWall = 141 UMETA(DisplayName="L Fixing Wall"),
    SO_L_FixingFloor = 147 UMETA(DisplayName="L Fixing Floor"),
    SO_L_CleaningWindowStand = 142 UMETA(DisplayName="L Cleaning Window Stand"),
    SO_L_CleaningWindowCrouch UMETA(DisplayName="L Cleaning Window Crouch"),
    SO_L_CleaningFloorCrouch = 146 UMETA(DisplayName="L Cleaning Floor Crouch"),
    SO_L_LeanWall_Back = 148 UMETA(DisplayName="L Lean Wall Back"),
    SO_L_LeanWall_Left UMETA(DisplayName="L Lean Wall Left"),
    SO_L_Lean_Fence_Front = 163 UMETA(DisplayName="L Lean Fence Front"),
    SO_L_LeanFence_Back = 152 UMETA(DisplayName="L Lean Fence Back"),
    SO_L_LeanTable_Front UMETA(DisplayName="L Lean Table Front"),
    SO_L_UsePrinter = 130 UMETA(DisplayName="L Use Printer"),
    SO_L_UseATM = 156 UMETA(DisplayName="L Use ATM"),
    SO_L_UseVendingMachine UMETA(DisplayName="L Use Vending Machine"),
    SO_L_UseCoffeeMachine UMETA(DisplayName="L Use Coffee Machine"),
    SO_L_UseDryer UMETA(DisplayName="L Use Dryer"),
    SO_L_UseTicketDispencer = 165 UMETA(DisplayName="L Use Ticket Dispencer"),
    SO_L_UseUrinal = 171 UMETA(DisplayName="L Use Urinal"),
    SO_L_WashHand = 160 UMETA(DisplayName="L Wash Hand"),
    SO_L_SearchTable = 166 UMETA(DisplayName="L Search Table"),
    SO_L_Discussion = 170 UMETA(DisplayName="L Discussion"),
};
