#pragma once
#include "CoreMinimal.h"
#include "EIGS_GangsterVariationType.generated.h"

UENUM(BlueprintType)
enum class EIGS_GangsterVariationType : uint8 {
    US_None UMETA(DisplayName=None),
    US_White UMETA(DisplayName=White),
    US_Black UMETA(DisplayName=Black),
    US_Russian UMETA(DisplayName=Russian),
    US_Sicarios UMETA(DisplayName=Sicarios),
    US_Hielo UMETA(DisplayName=Hielo),
    US_Riders UMETA(DisplayName=Riders),
    US_Scudos UMETA(DisplayName=Scudos),
    US_Specnaz UMETA(DisplayName=Specnaz),
    US_Contras UMETA(DisplayName=Contras),
    US_Vietcong UMETA(DisplayName=Vietcong),
    US_RussianSoldier UMETA(DisplayName="Russian Soldier"),
    US_ArabFighters UMETA(DisplayName="Arab Fighters"),
    US_Eastmen UMETA(DisplayName=Eastmen),
    US_FPSMaxIndex = 128 UMETA(DisplayName="FPS Max Index"),
    US_STO_Specnaz UMETA(DisplayName="STO Specnaz"),
    US_STO_Contras UMETA(DisplayName="STO Contras"),
    US_STO_Vietcong UMETA(DisplayName="STO Vietcong"),
    US_STO_Russians UMETA(DisplayName="STO Russians"),
    US_STO_Afghans UMETA(DisplayName="STO Afghans"),
    US_STO_Hielo UMETA(DisplayName="STO Hielo"),
    US_STO_WitchGoons UMETA(DisplayName="STO Witch Goons"),
    US_STO_Ronin UMETA(DisplayName="STO Ronin"),
    US_STO_PrisonOrg UMETA(DisplayName="STO Prison Org"),
    US_STO_EastMen UMETA(DisplayName="STO East Men"),
    US_STO_Sicarios UMETA(DisplayName="STO Sicarios"),
    US_STO_Riders UMETA(DisplayName="STO Riders"),
    US_STO_Scudos UMETA(DisplayName="STO Scudos"),
    US_Ninja UMETA(DisplayName=Ninja),
    US_STO_Bluebull UMETA(DisplayName="STO Bluebull"),
    US_STO_Latinos UMETA(DisplayName="STO Latinos"),
    US_STO_ExplosiveWG UMETA(DisplayName="STO Explosive WG"),
    US_Unknown = 255 UMETA(DisplayName=Unknown),
};
