#pragma once
#include "CoreMinimal.h"
#include "EIGS_CiviliansVariationType.generated.h"

UENUM(BlueprintType)
enum class EIGS_CiviliansVariationType : uint8 {
    US_None UMETA(DisplayName=None),
    US_Office UMETA(DisplayName=Office),
    US_Beach UMETA(DisplayName=Beach),
    US_Bank UMETA(DisplayName=Bank),
    US_Street UMETA(DisplayName=Street),
    US_StreetNight UMETA(DisplayName="Street Night"),
    US_WomenStreet UMETA(DisplayName="Women Street"),
    US_Homeless UMETA(DisplayName=Homeless),
    US_Workout UMETA(DisplayName=Workout),
    US_Workers UMETA(DisplayName=Workers),
    US_Fishers UMETA(DisplayName=Fishers),
    US_Laboratory UMETA(DisplayName=Laboratory),
    US_Strippers UMETA(DisplayName=Strippers),
    US_Beach_M UMETA(DisplayName="Beach M"),
    US_Beach_F UMETA(DisplayName="Beach F"),
    US_Bank_M UMETA(DisplayName="Bank M"),
    US_Bank_F UMETA(DisplayName="Bank F"),
    US_Street_M UMETA(DisplayName="Street M"),
    US_StreetNight_M UMETA(DisplayName="Street Night M"),
    US_StreetNight_F UMETA(DisplayName="Street Night F"),
    US_Homeless_M UMETA(DisplayName="Homeless M"),
    US_Homeless_F UMETA(DisplayName="Homeless F"),
    US_Workout_M UMETA(DisplayName="Workout M"),
    US_Workout_F UMETA(DisplayName="Workout F"),
    US_Fisher_M UMETA(DisplayName="Fisher M"),
    US_Fisher_F UMETA(DisplayName="Fisher F"),
    US_Bar UMETA(DisplayName=Bar),
    US_Bar_M UMETA(DisplayName="Bar M"),
    US_Bar_F UMETA(DisplayName="Bar F"),
    US_Beach_Shoes UMETA(DisplayName="Beach Shoes"),
    US_Beach_Shoes_M UMETA(DisplayName="Beach Shoes M"),
    US_Beach_Shoes_F UMETA(DisplayName="Beach Shoes F"),
    US_Workout_Shoeless UMETA(DisplayName="Workout Shoeless"),
    US_Workout_Shoeless_M UMETA(DisplayName="Workout Shoeless M"),
    US_Workout_Shoeless_F UMETA(DisplayName="Workout Shoeless F"),
    US_FPSMaxIndex = 128 UMETA(DisplayName="FPS Max Index"),
    US_STO_Satellite UMETA(DisplayName="STO Satellite"),
    US_STO_Laboratory UMETA(DisplayName="STO Laboratory"),
    US_STO_PrisonOrg UMETA(DisplayName="STO Prison Org"),
    US_STO_PrisonTwl UMETA(DisplayName="STO Prison Twl"),
    US_Unknown = 255 UMETA(DisplayName=Unknown),
};
