#include "HoudiniStaticMeshGenerationProperties.h"
#include "PhysicsEngine/BodyInstance.h"
#include "Engine/EngineTypes.h"
#include "Chaos/ChaosEngineInterface.h"

FHoudiniStaticMeshGenerationProperties::FHoudiniStaticMeshGenerationProperties() {
    (*this).bGeneratedDoubleSidedGeometry = false;
    (*this).GeneratedPhysMaterial = nullptr;
    auto gen = TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("ObjectType");
    (*gen->ContainerPtrToValuePtr<TEnumAsByte<ECollisionChannel>>(&(*this).DefaultBodyInstance, 0)) = ECC_WorldStatic;
    (*this).DefaultBodyInstance.SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
    (*this).DefaultBodyInstance.SleepFamily = ESleepFamily::Normal;
    (*this).DefaultBodyInstance.DOFMode = EDOFMode::Default;
    (*this).DefaultBodyInstance.bUseCCD = false;
    (*this).DefaultBodyInstance.bIgnoreAnalyticCollisions = false;
    (*this).DefaultBodyInstance.bNotifyRigidBodyCollision = false;
    (*this).DefaultBodyInstance.bLockTranslation = true;
    (*this).DefaultBodyInstance.bLockRotation = true;
    (*this).DefaultBodyInstance.bLockXTranslation = false;
    (*this).DefaultBodyInstance.bLockYTranslation = false;
    (*this).DefaultBodyInstance.bLockZTranslation = false;
    (*this).DefaultBodyInstance.bLockXRotation = false;
    (*this).DefaultBodyInstance.bLockYRotation = false;
    (*this).DefaultBodyInstance.bLockZRotation = false;
    (*this).DefaultBodyInstance.bOverrideMaxAngularVelocity = false;
    auto gen2 = TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("bOverrideMaxDepenetrationVelocity");
    CastField<FBoolProperty>(gen2)->SetPropertyValue(&(*gen2->ContainerPtrToValuePtr<uint8>(&(*this).DefaultBodyInstance, 0)), false);
    auto gen3 = TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("bOverrideWalkableSlopeOnInstance");
    CastField<FBoolProperty>(gen3)->SetPropertyValue(&(*gen3->ContainerPtrToValuePtr<uint8>(&(*this).DefaultBodyInstance, 0)), false);
    auto gen4 = TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("bInterpolateWhenSubStepping");
    CastField<FBoolProperty>(gen4)->SetPropertyValue(&(*gen4->ContainerPtrToValuePtr<uint8>(&(*this).DefaultBodyInstance, 0)), true);
    auto gen5 = TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionProfileName");
    (*gen5->ContainerPtrToValuePtr<FName>(&(*this).DefaultBodyInstance, 0)) = TEXT("BlockAll");
    (*this).DefaultBodyInstance.PositionSolverIterationCount = 8;
    (*this).DefaultBodyInstance.VelocitySolverIterationCount = 1;
    auto gen6 = TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses");
    auto gen7 = TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels");
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).WorldStatic = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).WorldDynamic = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).Pawn = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).Visibility = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).Camera = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).PhysicsBody = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).Vehicle = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).Destructible = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).EngineTraceChannel1 = ECR_Ignore;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).EngineTraceChannel2 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).EngineTraceChannel3 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).EngineTraceChannel4 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).EngineTraceChannel5 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).EngineTraceChannel6 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel1 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel2 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel3 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel4 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel5 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel6 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel7 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel8 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel9 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel10 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel11 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel12 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel13 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel14 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel15 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel16 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel17 = ECR_Block;
    (*gen7->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel18 = ECR_Block;
    FResponseChannel gen8;
    gen8.Channel = TEXT("Ping");
    FResponseChannel gen9;
    gen9.Channel = TEXT("Wheels");
    FResponseChannel gen10;
    gen10.Channel = TEXT("cover");
    auto gen11 = TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseArray");
    (*gen11->ContainerPtrToValuePtr<TArray<FResponseChannel>>(&(*gen6->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)) = TArray<FResponseChannel>{gen8, gen9, gen10};
    auto gen12 = TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("MaxDepenetrationVelocity");
    (*gen12->ContainerPtrToValuePtr<float>(&(*this).DefaultBodyInstance, 0)) = 0.000000000e+00f;
    auto gen13 = TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("MassInKgOverride");
    (*gen13->ContainerPtrToValuePtr<float>(&(*this).DefaultBodyInstance, 0)) = 1.000000000e+02f;
    (*this).DefaultBodyInstance.LinearDamping = 9.999999776e-03f;
    (*this).DefaultBodyInstance.AngularDamping = 0.000000000e+00f;
    (*this).DefaultBodyInstance.CustomDOFPlaneNormal.X = 0.000000000e+00f;
    (*this).DefaultBodyInstance.CustomDOFPlaneNormal.Y = 0.000000000e+00f;
    (*this).DefaultBodyInstance.CustomDOFPlaneNormal.Z = 0.000000000e+00f;
    (*this).DefaultBodyInstance.COMNudge.X = 0.000000000e+00f;
    (*this).DefaultBodyInstance.COMNudge.Y = 0.000000000e+00f;
    (*this).DefaultBodyInstance.COMNudge.Z = 0.000000000e+00f;
    (*this).DefaultBodyInstance.MassScale = 1.000000000e+00f;
    (*this).DefaultBodyInstance.InertiaTensorScale.X = 1.000000000e+00f;
    (*this).DefaultBodyInstance.InertiaTensorScale.Y = 1.000000000e+00f;
    (*this).DefaultBodyInstance.InertiaTensorScale.Z = 1.000000000e+00f;
    auto gen14 = TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("WalkableSlopeOverride");
    (*gen14->ContainerPtrToValuePtr<FWalkableSlopeOverride>(&(*this).DefaultBodyInstance, 0)).WalkableSlopeBehavior = WalkableSlope_Default;
    (*gen14->ContainerPtrToValuePtr<FWalkableSlopeOverride>(&(*this).DefaultBodyInstance, 0)).WalkableSlopeAngle = 0.000000000e+00f;
    auto gen15 = TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("PhysMaterialOverride");
    (*gen15->ContainerPtrToValuePtr<UPhysicalMaterial*>(&(*this).DefaultBodyInstance, 0)) = nullptr;
    (*this).DefaultBodyInstance.MaxAngularVelocity = 3.600000000e+03f;
    (*this).DefaultBodyInstance.CustomSleepThresholdMultiplier = 1.000000000e+00f;
    (*this).DefaultBodyInstance.StabilizationThresholdMultiplier = 1.000000000e+00f;
    (*this).DefaultBodyInstance.PhysicsBlendWeight = 0.000000000e+00f;
    (*this).DefaultBodyInstance.bSimulatePhysics = false;
    (*this).DefaultBodyInstance.bOverrideMass = false;
    (*this).DefaultBodyInstance.bEnableGravity = true;
    (*this).DefaultBodyInstance.bAutoWeld = false;
    (*this).DefaultBodyInstance.bStartAwake = true;
    (*this).DefaultBodyInstance.bGenerateWakeEvents = false;
    (*this).DefaultBodyInstance.bUpdateMassWhenScaleChanges = false;
    (*this).GeneratedCollisionTraceFlag = CTF_UseDefault;
    (*this).GeneratedLightMapResolution = 64;
    (*this).GeneratedWalkableSlopeOverride.WalkableSlopeBehavior = WalkableSlope_Default;
    (*this).GeneratedWalkableSlopeOverride.WalkableSlopeAngle = 0.000000000e+00f;
    (*this).GeneratedLightMapCoordinateIndex = 1;
    (*this).bGeneratedUseMaximumStreamingTexelRatio = false;
    (*this).GeneratedStreamingDistanceMultiplier = 1.000000000e+00f;
    (*this).GeneratedFoliageDefaultSettings = nullptr;
    (*this).GeneratedAssetUserData = TArray<UAssetUserData*>{};
}
