#pragma once
#include "CoreMinimal.h"
#include "EIGS_InputAction.generated.h"

UENUM(BlueprintType)
enum class EIGS_InputAction : uint8 {
    IA_UNKNOWN = 255 UMETA(DisplayName=UNKNOWN),
    IA_MoveForward = 0 UMETA(DisplayName="Move Forward"),
    IA_MoveBackwards UMETA(DisplayName="Move Backwards"),
    IA_MoveLeft UMETA(DisplayName="Move Left"),
    IA_MoveRight UMETA(DisplayName="Move Right"),
    IA_Jump UMETA(DisplayName=Jump),
    IA_Crouch UMETA(DisplayName=Crouch),
    IA_Sprint UMETA(DisplayName=Sprint),
    IA_Aim UMETA(DisplayName=Aim),
    IA_Shoot UMETA(DisplayName=Shoot),
    IA_InspectWeapon UMETA(DisplayName="Inspect Weapon"),
    IA_Reload UMETA(DisplayName=Reload),
    IA_SwitchFireMode UMETA(DisplayName="Switch Fire Mode"),
    IA_Use UMETA(DisplayName=Use),
    IA_Bash UMETA(DisplayName=Bash),
    IA_CharacterMenu UMETA(DisplayName="Character Menu"),
    IA_BotMenuPossess UMETA(DisplayName="Bot Menu Possess"),
    IA_BotMenuCancel UMETA(DisplayName="Bot Menu Cancel"),
    IA_BotMenuFollow UMETA(DisplayName="Bot Menu Follow"),
    IA_BotMenuStandBy UMETA(DisplayName="Bot Menu Stand By"),
    IA_WeaponWheel UMETA(DisplayName="Weapon Wheel"),
    IA_NextWeapon UMETA(DisplayName="Next Weapon"),
    IA_PreviousWeapon UMETA(DisplayName="Previous Weapon"),
    IA_PrimaryWeapon UMETA(DisplayName="Primary Weapon"),
    IA_SecondaryWeapon UMETA(DisplayName="Secondary Weapon"),
    IA_MeleeWeapon UMETA(DisplayName="Melee Weapon"),
    IA_SpecialAction1 UMETA(DisplayName="Special Action 1"),
    IA_SwitchWeapon UMETA(DisplayName="Switch Weapon"),
    IA_Approve UMETA(DisplayName=Approve),
    IA_EnterChat UMETA(DisplayName="Enter Chat"),
    IA_Ping UMETA(DisplayName=Ping),
    IA_Walk UMETA(DisplayName=Walk),
    IA_DropCarryable UMETA(DisplayName="Drop Carryable"),
    IA_Holster UMETA(DisplayName=Holster),
    IA_Shout UMETA(DisplayName=Shout),
    IA_MenuLeft UMETA(DisplayName="Menu Left"),
    IA_MenuRight UMETA(DisplayName="Menu Right"),
    IA_MenuBack UMETA(DisplayName="Menu Back"),
    IA_MenuAccept UMETA(DisplayName="Menu Accept"),
    IA_MenuMiscAction1 UMETA(DisplayName="Menu Misc Action 1"),
    IA_MenuMiscAction2 UMETA(DisplayName="Menu Misc Action 2"),
    IA_MenuCategoryLeft UMETA(DisplayName="Menu Category Left"),
    IA_MenuCategoryRight UMETA(DisplayName="Menu Category Right"),
    IA_MenuSubcategoryLeft UMETA(DisplayName="Menu Subcategory Left"),
    IA_MenuSubcategoryRight UMETA(DisplayName="Menu Subcategory Right"),
    IA_MenuPause UMETA(DisplayName="Menu Pause"),
    IA_PartyInvite UMETA(DisplayName="Party Invite"),
    IA_Skip UMETA(DisplayName=Skip),
    IA_MenuUp UMETA(DisplayName="Menu Up"),
    IA_MenuDown UMETA(DisplayName="Menu Down"),
    IA_MountLeft UMETA(DisplayName="Mount Left"),
    IA_MountRight UMETA(DisplayName="Mount Right"),
    IA_MountUp UMETA(DisplayName="Mount Up"),
    IA_MountDown UMETA(DisplayName="Mount Down"),
    IA_MountPrimary UMETA(DisplayName="Mount Primary"),
    IA_MountSecondary UMETA(DisplayName="Mount Secondary"),
    IA_MountTertiary UMETA(DisplayName="Mount Tertiary"),
    IA_MountQuaternary UMETA(DisplayName="Mount Quaternary"),
    IA_Lockpick UMETA(DisplayName=Lockpick),
    IA_WheelMenu UMETA(DisplayName="Wheel Menu"),
    IA_PushToTalk UMETA(DisplayName="Push To Talk"),
};
