#include "META_CharacterData.h"
#include "GameplayTagContainer.h"

FMETA_CharacterData::FMETA_CharacterData() {
    (*this).GenericVariantID = -1;
    (*this).Name = FText::GetEmpty();
    (*this).Surname = FText::GetEmpty();
    (*this).MetaCharacterIcon = FSoftObjectPath();
    (*this).Quality = EMETA_ItemQuality::None;
    (*this).Level = 1;
    (*this).CanLevelUp = true;
    (*this).BaseUpkeepCost = 0;
    (*this).BaseMissionCutPercent = 0;
    (*this).MaxLeveled = false;
    (*this).BaseHireCost = 0;
    (*this).WeaponsCostCoefficient = 1.000000000e+00f;
    (*this).JobsCanBeCompletedPerDay = 1;
    (*this).Description = FText::GetEmpty();
    (*this).Injuries = 0;
    (*this).State = EMETA_CharacterState::None;
    (*this).Mood = EMETA_CharacterMood::Neutral;
    auto gen = TBaseStructure<FGameplayTagContainer>::Get()->FindPropertyByName("GameplayTags");
    (*gen->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).Traits, 0)) = {};
    auto gen2 = TBaseStructure<FGameplayTagContainer>::Get()->FindPropertyByName("ParentTags");
    (*gen2->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).Traits, 0)) = {};
    (*this).Perks = {};
    (*this).ChangedHeisterAttributes = {};
    (*this).Class = nullptr;
    (*this).Attributes.MaxHealth = 960;
    (*this).Attributes.ReviveCount = 3;
    auto gen3 = TBaseStructure<FGameplayTagQuery>::Get()->FindPropertyByName("TokenStreamVersion");
    (*gen3->ContainerPtrToValuePtr<int32>(&(*this).Attributes.AllowedWieldables, 0)) = 0;
    FGameplayTag gen4;
    auto gen5 = TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName");
    (*gen5->ContainerPtrToValuePtr<FName>(&gen4, 0)) = TEXT("Item.Wieldable");
    auto gen6 = TBaseStructure<FGameplayTagQuery>::Get()->FindPropertyByName("TagDictionary");
    (*gen6->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).Attributes.AllowedWieldables, 0)) = {MoveTemp(gen4)};
    auto gen7 = TBaseStructure<FGameplayTagQuery>::Get()->FindPropertyByName("QueryTokenStream");
    (*gen7->ContainerPtrToValuePtr<TArray<uint8>>(&(*this).Attributes.AllowedWieldables, 0)) = {0, 1, 2, 1, 0};
    auto gen8 = TBaseStructure<FGameplayTagQuery>::Get()->FindPropertyByName("UserDescription");
    (*gen8->ContainerPtrToValuePtr<FString>(&(*this).Attributes.AllowedWieldables, 0)) = TEXT("");
    auto gen9 = TBaseStructure<FGameplayTagQuery>::Get()->FindPropertyByName("AutoDescription");
    (*gen9->ContainerPtrToValuePtr<FString>(&(*this).Attributes.AllowedWieldables, 0)) = TEXT("");
    (*this).Variables = {};
    (*this).Loadout.PrimaryWeapon = nullptr;
    (*this).Loadout.PrimaryWeaponClass = nullptr;
    (*this).Loadout.PrimaryPersonalWeapons = {};
    (*gen5->ContainerPtrToValuePtr<FName>(&(*this).Loadout.PrimaryWeaponSkin, 0)) = NAME_None;
    (*this).Loadout.PrimaryPersonalWeaponsClass = {};
    (*this).Loadout.SecondaryWeapon = nullptr;
    (*this).Loadout.SecondaryWeaponClass = nullptr;
    (*this).Loadout.SecondaryPersonalWeapons = {};
    (*gen5->ContainerPtrToValuePtr<FName>(&(*this).Loadout.SecondaryWeaponSkin, 0)) = NAME_None;
    (*this).Loadout.SecondaryPersonalWeaponsClass = {};
    (*this).Loadout.SelectedEquipment = nullptr;
    (*this).Loadout.ChainEquipments = {};
    (*this).Loadout.ChainEquipmentsObjects = {};
    (*gen5->ContainerPtrToValuePtr<FName>(&(*this).Loadout.CharacterSkin, 0)) = NAME_None;
    (*this).Loadout.Ability1ChargesLeft = -1;
    (*this).MissionsWasPlayed = 0;
    (*this).MutableVariationIndex = -1;
    (*this).TimesHealed = 0;
    (*this).bTemporary = false;
    (*this).bLocked = false;
    (*this).BaseLevelUpMultiplier = 0.000000000e+00f;
}
